version: "2"
services:
  show-dev:
    container_name: show-dev
    build:
      context: .
    links:
      - redis
    volumes:
      - .:/go/src/show
    command: "go run main.go"
    ports:
      - 20001:20001
    depends_on:
      - "redis"
    environment:
      DEBUG: "1"
    entrypoint: ./wait-for-it.sh redis:6379 --strict --timeout=120 --
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .:/data